spring.application.name=WalletManager

# db
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# liquibae
spring.liquibase.enabled=true

# path to changelogs
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# coonect
spring.liquibase.url=jdbc:postgresql://localhost:5432/wallet_db
spring.liquibase.user=postgres
spring.liquibase.password=root